---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gobg-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abu-raed/gitops-masterclass-applications-template
    targetRevision: main
    path: kustomize/env/overlays/stage/
  destination:
    namespace: gobg-stage
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
